# Generated by Django 5.2.4 on 2025-08-11 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="telegram_chat",
            new_name="chat_id",
        ),
    ]
