# Generated by Django 5.2.4 on 2025-08-06 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "place",
                    models.CharField(
                        help_text="Укажите Ваше местонахождение", max_length=100
                    ),
                ),
                ("time", models.TimeField()),
                (
                    "action",
                    models.CharField(help_text="Укажите Ваше действие", max_length=200),
                ),
                ("is_pleasant", models.BooleanField(default=False)),
                ("frequency", models.PositiveIntegerField(default=1)),
                ("reward", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "duration",
                    models.PositiveIntegerField(
                        help_text="Продолжительность в секундах"
                    ),
                ),
                ("is_public", models.BooleanField(default=False)),
                (
                    "related_habit",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"is_pleasant": True},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="habits.habit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
            },
        ),
    ]
