# Generated by Django 5.2.4 on 2025-08-11 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="frequency",
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
